name: Workflow Practica-1

on:
  push:
    branches:
      - master

jobs:
  preactica-1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Pruebas de SAST
        run: echo "Ejecución de pruebas de SAST"

      - name: Crear archivo de credenciales
        run: |
          echo "[credentials]" > credentials.ini
          echo "username=${{ secrets.USERNAME }}" >> credentials.ini
          echo "password=${{ secrets.PASSWORD }}" >> credentials.ini

      - name: Build docker image
        run: docker build -t devops_ws . --tag devops_ws_:$(date +%s)
