name: Workflow Practica-1

on:
  push:
    branches:
      - master
      - hotfix
      - feature*

jobs:
  practica-1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Pruebas de SAST
        run: echo "Ejecución de pruebas de SAST"

      - name: Crear archivo de credenciales
        env: 
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: envsubst < credentials.ini.tpl > credentials.ini

      - name: Build docker image
        run: docker build -t devops_ws . --tag devops_ws_$(date +%s)
